# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    JMS\Serializer\SerializerInterface: '@jms_serializer'

    App\Repository\TaskRepository:
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - 'App\Entity\Task'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\ArgumentValueResolver\Auth\UserRegisterResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    App\ArgumentValueResolver\Task\CreateTaskResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    App\ArgumentValueResolver\Task\EditTaskResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    App\Service\Task\TaskFinder:
        calls:
            - ['addFilter', ['@App\Doctrine\Filter\PriorityFilter', 'priority']]
            - ['addFilter', ['@App\Doctrine\Filter\StatusFilter', 'status']]
            - ['addFilter', ['@App\Doctrine\Filter\TitleFilter', 'title']]

